Monitoring usage of a device
iis-powp-2021-ffc-backup/powp_jobs2d_projects pull request #14
Opened 2021-04-14 16:48 UTC by Whitesan

2021-04-20 12:42 UTC, kowallus requested changes
Lack of OCP

2021-04-20 12:42 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/LineDriverAdapter.java
> +
You shouldn't change existing drivers (OCP). Find another solution

2021-04-20 12:42 UTC, kowallus commented on src/test/java/edu/kis/powp/legacy/drawer/TestDistanceMonitor.java
> +public class TestDistanceMonitor {
Try to develop a test that works also in TestApp GUI.

2021-04-21 07:18 UTC, kowallus requested changes
Minor code cleaning in tests

2021-04-21 07:18 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/UsageMonitoringDriver.java
> +public class UsageMonitoringDriver extends LineDriverAdapter {
Decorator approach would be more flexible.

2021-04-21 07:18 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectMonitoringDeviceTestFigureOptionListener.java
> +				.execute(driver);
Why do you create commands instead of working on driver directly. I you want to create command make it reusable (e.g., small command factory).

2021-04-21 07:18 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/SelectMonitoringDeviceTestFigureOptionListener.java
> +			if (usageMonitoringDriver.getOpDistance() != 200 || usageMonitoringDriver.getHeadDistance() != 400) {
Are you certain that before starting a test UsageMonitoringDriver would be in the initial state?
BTW: I think that you could use constants here to make the test more readable.

2021-04-21 09:52 UTC, kowallus commented
You shouldn't close this PR :(. PR 23 does not have my comments. Could you reopen?

2021-04-21 11:06 UTC, Whitesan commented
Tak już to zrobiłem

2021-04-21 11:39 UTC, merged