Added drivers composite
iis-powp-2021-ffc-backup/powp_jobs2d_projects pull request #15
Opened 2021-04-14 21:06 UTC by piotr-s-nowak

2021-04-20 12:46 UTC, kowallus requested changes
Some code clean up required

2021-04-20 12:46 UTC, kowallus commented on jobs2d.iml
> +<?xml version="1.0" encoding="UTF-8"?>
unnecessary project file (REMOVE)

2021-04-20 12:46 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/CompositeDriver.java
> +    public List getChildren(){
Why without a template? 
It is better to return a list copy so it cannot be modified from outside.

2021-04-21 11:46 UTC, piotr-s-nowak commented
changes commited

2021-05-12 10:49 UTC, piotr-s-nowak commented
conflicts resolved

2021-05-12 10:59 UTC, merged