Observer for a driver changes events
iis-powp-2021-ffc-backup/powp_jobs2d_projects pull request #24
Opened 2021-04-21 10:13 UTC by ImAStudentAtUniversity

2021-04-21 10:41 UTC, kowallus requested changes
minor code cleanup

2021-04-21 10:41 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/observer/DriverChangeObserver.java
> +public class DriverChangeObserver implements Subscriber{
The name of the observer should explain what is its purpose!

2021-04-21 10:41 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +				DriverFeature.addDriverChangeObserver(new DriverChangeObserver(app));
please add this line to setupDriverPlugin method (it is its place)

2021-04-21 11:35 UTC, kowallus requested changes
one more

2021-04-21 11:35 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +				DriverFeature.setupDriverPlugin(app, new DriverNameUpdateObserver(app));
new DriverNameUpdateObserver(app) please put it also in setup method! (as a separate variable!)

2021-04-21 12:04 UTC, ImAStudentAtUniversity commented
Przez przypadek zduplikowały się nasze poprzednie commity, ale wszystko powinno się zgadzać. Zmergowałem commity z iis-powp-2021:io1-dev do ImAStudentAtUniversity:io1-dev po czym dokonałem rebase lokalnego brancha na którym pracowałem z ImAStudentAtUniversity:master do ImAStudentAtUniversity:io1-dev i zrobiłem pusha na ImAStudentAtUniversity:master.

2021-04-23 11:24 UTC, kowallus approved these changes
ok

2021-04-23 11:24 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DriverFeature.java
> +		driverManager.getPublisher().addSubscriber(new DriverNameUpdateObserver(app));
I would prefer defining a local variable ;)

2021-04-23 11:24 UTC, merged