Convert mouse clicks to driver calls #3
iis-powp-2021-ffc-backup/powp_jobs2d_projects pull request #41
Opened 2021-05-12 11:08 UTC by Blemm13

2021-05-12 11:17 UTC, kowallus requested changes
minor thing

2021-05-12 11:17 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/MouseClickAdapter.java
> +            driverManager.getCurrentDriver().setPosition(x, y);
minor code duplication

2021-05-12 11:17 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +		application.getFreePanel().addMouseListener(mouseClickAdapter);
it would be clearer if this has been done using:
mouseClickAdapter.enable()
or (the simplest solution) in a constructor.

2021-05-12 11:31 UTC, Blemm13 commented
Fixed

2021-05-13 11:04 UTC, kowallus requested changes
please fix quickly and resolve conflicts (and test!)

2021-05-13 11:04 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/adapter/MouseClickAdapter.java
> +    public void enable(JPanel jPanel) {
unnecessary parameter

2021-05-26 10:48 UTC, closed without merging